image: python:3.12

stages:
  - lint
  - build
  - deploy

before_script:
  - pip install -r requirements.txt


lint:
  stage: lint
  script:
    - pip install flake8
    - cd Services
    - flake8 .
  
  
  
