{{- range .Values.deployment}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
spec:
  replicas: {{  .replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- with .Labels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
  template:
    metadata:
      labels:
        {{- with .Labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .containerName }}
          image: {{ .image }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: {{ .containerPort }}
              protocol: TCP
          {{- if .volumeMounts }}
          volumeMounts:
          {{- toYaml .volumeMounts | nindent 10 }}
          {{- end }}
      {{- if .volumes }}
      volumes:
      {{- toYaml .volumes | nindent 6 }}
      {{- end }}
{{- end }}
