apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: service-monitor
  labels:
    release: prometheus  
spec:
  selector:
    matchLabels:
      app: bookings  
  endpoints:
  - port: metrics 
    path: /metrics
    interval: 15s