{{- range .Values.service}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name | quote }}
  labels:
  {{- with .selector }}
  {{- toYaml . | nindent 6 }}
  {{- end }}
spec:
  ports:
    {{- range .ports}}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .port }}
      protocol: TCP
    {{- end }}
  selector: 
  {{- with .selector }}
  {{- toYaml . | nindent 6 }}
  {{- end }}
{{- end }}
