apiVersion: v1
kind: Secret
metadata:
  name: db-secret
data:
  .env: REJfVVNFUj0icG9zdGdyZXMuZHBxZGhtaml0aXVsY3BzdWdnamUiIApEQl9QQVNTV09SRD0iYkNTTnhPRlluUVlEMVVaRiIKREJfSE9TVD0iYXdzLTAtZXUtd2VzdC0yLnBvb2xlci5zdXBhYmFzZS5jb20iCkRCX1BPUlQ9IjY1NDMiIApEQl9OQU1FPSJwb3N0Z3JlcyI=