# Default values for microservices.

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

deployment:
  - name: bookings-deployment
    Labels:
      app: bookings
    image: jerryelikem/bookings-service:latest
    containerName: bookings
    containerPort: 4004
   
  - name: movies-deployment 
    Labels:
      app: movies
    image: jerryelikem/movies-service:latest
    containerName: movies
    containerPort: 4001

  - name: users-deployment
    replicaCount: 2 
    Labels:
      app: users
    image: jerryelikem/users-service:latest
    containerName: users
    containerPort: 4007
    volumes: 
      - name: shared-data
        emptyDir: {}
    volumeMounts:
      - name: shared-data 
        mountPath: /usr/share/data 

service:
  - name: movies-service
    selector: movies
    port: 4001
  - name: bookings-service
    selector: bookings
    port: 4004
  - name: users-service
    selector: users
    port: 4007


ingress:
  name: microservice-demo-ingress
  enabled: true
  className: ""
  annotations: {}
  paths:
    - path: /users
      service_name: users-service
      service_port: 4007
    - path: /bookings
      service_name: bookings-service
      service_port: 4004
    - path: /movies
      service_name: movies-service
      service_port: 4001
  
    
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80



nodeSelector: {}

tolerations: []

affinity: {}
